server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: dummy_service_route
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/dummy/**
          filters:
            - StripPrefix=1